server:
  port: 8181
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nisal-kumara/spring-cloud-config-store
          search-paths:
           - '*service'



